name: damnit-web-local

services:
  app:
    extends:
      file: ./compose.base.yml
      service: app
    build:
      target: preview
      args:
        PREVIEW_PORT: ${APP_PREVIEW_PORT:-4173}
        SITE_URL: https://damnit-dev.xfel.eu
        API_URL: http://host.docker.internal:8123/
    ports:
      - ${APP_PREVIEW_PORT:-4173}:${APP_PREVIEW_PORT:-4173}
