name: damnit-web-local

services:
  frontend:
    extends:
      file: ./compose.base.yml
      service: frontend
    build:
      target: preview
    environment:
      - VITE_API=http://host.docker.internal:8123/
    ports:
      - 4173:4173
