name: damnit-web-dev

networks:
  proxy:
    external: true

services:
  frontend:
    extends:
      file: ./compose.base.yml
      service: frontend
    build:
      target: preview
    environment:
      - VITE_API=http://max-exfl463.desy.de:8123
    volumes:
      - ./certs:/certs
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.damnit_web_dev.rule=(Host(`damnit-dev.exfldadev01.desy.de`) || Host(`damnit-dev.xfel.eu`))'
      - 'traefik.http.services.damnit_web_dev.loadbalancer.server.port=4173'
