name: damnit-web-local

services:
  site:
    extends:
      file: ./compose.base.yml
      service: site
    build:
      target: preview
      args:
        PREVIEW_PORT: ${SITE_PREVIEW_PORT:-4173}
        APP_URL: https://damnit-dev.xfel.eu
    ports:
      - ${SITE_PREVIEW_PORT:-4173}:${SITE_PREVIEW_PORT:-4173}
