site_name: DAMNIT Web API
site_description: DAMNIT Web API Documentation

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.instant

repo_url: https://github.com/European-XFEL/DAMNIT-web.git

watch:
  - ./README.md

markdown_extensions:
  - pymdownx.snippets

plugins:
  - search
