site_name: DAMNIT Web API
site_description: DAMNIT Web API Documentation

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.sections

repo_url: https://github.com/European-XFEL/DAMNIT-web.git

nav:
  - index.md
  - Deployment: deployment.md
  - Development:
    - ./dev/setup.md
    - ./dev/ci-cd.md
    - ./dev/docs.md
    - ./dev/architecture.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
